/*
Copyright Nik Sultana, 2019

This file is part of TYM Datalog. (https://www.github.com/niksu/tym)

TYM Datalog is free software: you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TYM Datalog is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details, a copy of which
is included in the file called LICENSE distributed with TYM Datalog.

You should have received a copy of the GNU Lesser General Public License
along with TYM Datalog.  If not, see <https://www.gnu.org/licenses/>.


This file: Translating parsed Datalog into C code.
*/

#include <time.h>

#include "ast.h"
#include "formula.h"
#include "interface_c.h"
#include "output_c.h"
#include "support.h"

static void
timestamp(char * charbuff, size_t charbuff_len)
{
  time_t now = time(NULL);
  if ((time_t)-1 == now) {
    exit(TYM_TIMESTAMP_ERROR);
  }

  struct tm * now_calendar = localtime(&now);
  if (NULL == now_calendar) {
    exit(TYM_TIMESTAMP_ERROR);
  }

  if (!strftime(charbuff, charbuff_len, "%A %c %z", now_calendar)) {
    exit(TYM_TIMESTAMP_ERROR);
  }
}

void
emit_c_program(struct TymProgram * ParsedInputFileContents,
  struct TymProgram * ParsedQuery)
{
  struct TymSymGen * ng = tym_mk_sym_gen(TYM_CSTR_DUPLICATE("var"));
  const struct TymCSyntax * csyn_program = tym_csyntax_program(ng, ParsedInputFileContents);
  const struct TymCSyntax * csyn_query = tym_csyntax_program(ng, ParsedQuery);

  char charbuff[TYM_BUF_SIZE];
  timestamp(charbuff, TYM_BUF_SIZE);
  printf("// Generated by Tym Datalog version %d.%d at %s\n\n", TYM_VERSION_MAJOR, TYM_VERSION_MINOR, charbuff);
  printf("#include \"tym.h\"\n\n");
  printf("enum TymReturnCode\n");
  printf("apply (enum TymReturnCode (*meta_program)(struct TymParams * Params, struct TymProgram * program, struct TymProgram * query), struct TymParams * Params)\n");
  printf("{\n");
  printf("// Program\n%s\n", tym_decode_str(csyn_program->serialised));
  printf("// Query\n%s\n", tym_decode_str(csyn_query->serialised));
  printf("struct TymProgram * program = &%s;\n", tym_decode_str(csyn_program->name));
  printf("struct TymProgram * query = &%s;\n", tym_decode_str(csyn_query->name));
  printf("return meta_program(Params, program, query);\n");
  printf("}\n");

  tym_free_sym_gen(ng);
  tym_csyntax_free(csyn_program);
  tym_csyntax_free(csyn_query);
}
