/*
 * Translating parsed Datalog into C code.
 * Nik Sultana, April 2018.
 *
 * This is part of TYM Datalog (https://www.github.com/niksu/tym)
 *
 * License: LGPL version 3 (for licensing terms see the file called LICENSE)
 */

#include "ast.h"
#include "formula.h"
#include "interface_c.h"
#include "output_c.h"
#include "support.h"

void
emit_c_program(struct TymProgram * ParsedInputFileContents,
  struct TymProgram * ParsedQuery)
{
  struct TymSymGen * ng = tym_mk_sym_gen(TYM_CSTR_DUPLICATE("var"));
  const struct TymCSyntax * csyn_program = tym_csyntax_program(ng, ParsedInputFileContents);
  const struct TymCSyntax * csyn_query = tym_csyntax_program(ng, ParsedQuery);

  // FIXME include date+time when output was generated.
  printf("// Generated by Tym Datalog version %d.%d\n\n", TYM_VERSION_MAJOR, TYM_VERSION_MINOR);
  printf("#include \"tym.h\"\n\n");
  printf("void\n");
  printf("apply (void (*meta_program)(struct TymParams * Params, struct TymProgram * program, struct TymProgram * query), struct TymParams * Params)\n");
  printf("{\n");
  printf("// Program\n%s\n", tym_decode_str(csyn_program->serialised));
  printf("// Query\n%s\n", tym_decode_str(csyn_query->serialised));
  printf("struct TymProgram * program = &%s;\n", tym_decode_str(csyn_program->name));
  printf("struct TymProgram * query = &%s;\n", tym_decode_str(csyn_query->name));
  printf("meta_program(Params, program, query);\n");
  printf("}\n");

  tym_free_sym_gen(ng);
  tym_csyntax_free(csyn_program);
  tym_csyntax_free(csyn_query);
}

